apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jmsight-wordpress
  labels:
    jmsight/name: jmsight-wordpress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: wordpress
                port:
                  number: 80