apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
spec:
  selector:
    component: elasticsearch
  externalTrafficPolicy: Local
  type: NodePort
  ports:
    - name: es-port
      port: 9200
      targetPort: 9200
      protocol: TCP
      nodePort: 30920
